from __future__ import annotations

from ui.postit.layout import (
    POSTIT_CALENDAR_ICON_SIZE,
    POSTIT_CALENDAR_POPUP_OFFSET_Y,
    POSTIT_DELETE_BUTTON_MARGIN_RIGHT,
    POSTIT_DELETE_BUTTON_MARGIN_TOP,
    POSTIT_PARTNER_LINK_ICON_SIZE,
    POSTIT_UNIT_DOWN_ICON_SIZE,
)


class PostItLayout:
    DATE_MIN_WIDTH_EXTRA = 8
    CALENDAR_ICON_SIZE = POSTIT_CALENDAR_ICON_SIZE
    PARTNER_LINK_ICON_SIZE = POSTIT_PARTNER_LINK_ICON_SIZE
    UNIT_ICON_SIZE = POSTIT_UNIT_DOWN_ICON_SIZE
    CALENDAR_POPUP_OFFSET_Y = POSTIT_CALENDAR_POPUP_OFFSET_Y
    DELETE_BUTTON_MARGIN_RIGHT = POSTIT_DELETE_BUTTON_MARGIN_RIGHT
    DELETE_BUTTON_MARGIN_TOP = POSTIT_DELETE_BUTTON_MARGIN_TOP
