from __future__ import annotations


class DialogLayout:
    MIN_WIDTH_NARROW = 420
    MIN_WIDTH_STANDARD = 460
    FORM_HORIZONTAL_SPACING = 12
    FORM_VERTICAL_SPACING = 10
    INLINE_ROW_SPACING = 6
    PRICE_GRID_SPACING = 10
    FIELD_HEIGHT = 30
    BUTTON_ICON_SIZE = 14
    STATUS_ICON_WIDTH = 18
    STATUS_ROW_SPACING = 6
    CALENDAR_POPUP_OFFSET_Y = 2
    PRICE_FIELD_MIN_WIDTH = 90
    PRICE_FIELD_MAX_WIDTH = 140
    UNIT_COMBO_MIN_WIDTH = 160


class OrderPageLayout:
    MONTH_COMBO_WIDTH = 150
    FILTER_INLINE_GAP = 6
    TEMPLATE_LIST_SPACING = 6
    IMAGE_SHELL_MARGIN = 14
    DETAIL_GRID_HORIZONTAL_SPACING = 10
    DETAIL_GRID_VERTICAL_SPACING = 8
    TEMPLATE_CARD_MARGIN = 12
    TEMPLATE_CARD_SPACING = 4


class PartnerLayout:
    BROWSER_WIDTH = 920
    BROWSER_HEIGHT = 640
    DIALOG_WIDTH = BROWSER_WIDTH
    DIALOG_HEIGHT = BROWSER_HEIGHT
    CARD_MARGIN = 16
    CARD_ROW_SPACING = 10
    CONTENT_SPACING = 12
    DETAIL_CARD_SPACING = 12
    DETAIL_LABEL_WIDTH = 54
    FIELD_EXTRA_HEIGHT = 6
    FORM_MARGIN = 18
    TYPE_SECTION_SPACING = 10
    MEMO_HEIGHT = 120
    TYPE_BADGE_ROW_SPACING = 4
    TYPE_BADGE_SIZE = 16
    TYPE_BADGE_RADIUS = 4
    TYPE_BADGE_FONT_PX = 10
    LIST_ITEM_MARGIN_H = 8
    LIST_ITEM_MARGIN_TOP = 7
    LIST_ITEM_MARGIN_BOTTOM = 7
    LIST_ITEM_SPACING = 6
    TYPE_GRID_HORIZONTAL_SPACING = 10
    TYPE_GRID_VERTICAL_SPACING = 8


class MenuLayout:
    CARD_HEIGHT_EXTRA = 18
    PAGE_MARGIN_X_OFFSET = 4
    PAGE_MARGIN_TOP = 22
    PAGE_MARGIN_BOTTOM = 18
    FOOTER_PRIMARY_WIDTH_EXTRA = 10
    FOOTER_BUTTON_HEIGHT_EXTRA = 2


class UnitDialogLayout:
    ICON_FONT_PX = 18
    MIN_ROWS = 20


class PartnerTypeDialogLayout:
    WIDTH = 540
    HEIGHT = 420
    ICON_FONT_PX = 18
    MIN_ROWS = 16
